<?php
/**
 * generate-autoload.php
 * Gera autoload PSR-4 manualmente sem precisar do Composer
 * Execute: php generate-autoload.php
 */

$projectRoot = __DIR__;
$autoloadFile = $projectRoot . '/vendor/composer/autoload_psr4.php';

// Garante que o diretório existe
@mkdir(dirname($autoloadFile), 0755, true);

// Configuração PSR-4
$psr4 = [
    'App\\' => 'app/',
    'App\\Model\\' => 'app/Model/',
    'App\\Controller\\' => 'app/Controller/',
    'App\\View\\' => 'app/View/',
    'Core\\' => 'Core/',
];

// Gera conteúdo do arquivo
$content = "<?php\n\n// This file is auto-generated by generate-autoload.php\n\nreturn array(\n";

foreach ($psr4 as $namespace => $path) {
    $fullPath = $projectRoot . '/' . $path;
    $content .= "    '{$namespace}' => array(\n";
    $content .= "        0 => \__DIR__ . '/../../{$path}',\n";
    $content .= "    ),\n";
}

$content .= ");\n";

// Gera autoload_classmap.php
$classMapFile = $projectRoot . '/vendor/composer/autoload_classmap.php';
$classMapContent = "<?php\n\n// This file is auto-generated by generate-autoload.php\n\nreturn array();\n";

// Gera autoload_files.php com os arquivos de configuração
$filesFile = $projectRoot . '/vendor/composer/autoload_files.php';
$filesContent = "<?php\n\n// This file is auto-generated by generate-autoload.php\n\nreturn array(\n";
$filesContent .= "    '{$projectRoot}/Config/db/conexao.php' => true,\n";
$filesContent .= "    '{$projectRoot}/Core/autenticacao.php' => true,\n";
$filesContent .= ");\n";

// Gera arquivo principal de autoload
$mainAutoloadFile = $projectRoot . '/vendor/composer/autoload_real.php';
$mainContent = <<<'PHP'
<?php

// This file is auto-generated by generate-autoload.php

class ComposerAutoloaderInit
{
    private static $loader;

    public static function getLoader()
    {
        if (null === self::$loader) {
            self::$loader = new \Composer\Autoload\ClassLoader();
            $dir = __DIR__ . '/..';
            
            // Carrega mapeamento PSR-4
            $psr4 = require $dir . '/composer/autoload_psr4.php';
            foreach ($psr4 as $prefix => $paths) {
                self::$loader->addPsr4($prefix, $paths);
            }
            
            // Carrega arquivos
            $files = require $dir . '/composer/autoload_files.php';
            foreach ($files as $file => $dummy) {
                require_once $file;
            }
        }

        return self::$loader;
    }
}

if (!class_exists('Composer\Autoload\ClassLoader', false)) {
    require __DIR__ . '/ClassLoader.php';
}

return ComposerAutoloaderInit::getLoader();
PHP;

// Gera namespace mock para Composer se não existir
if (!file_exists($projectRoot . '/vendor/composer/ClassLoader.php')) {
    $classLoaderContent = <<<'PHP'
<?php

namespace Composer\Autoload;

class ClassLoader
{
    private $prefixes = [];
    private $psr4 = [];

    public function addPsr4($prefix, $paths)
    {
        if (!isset($this->psr4[$prefix])) {
            $this->psr4[$prefix] = [];
        }
        
        if (is_array($paths)) {
            $this->psr4[$prefix] = array_merge($this->psr4[$prefix], $paths);
        } else {
            $this->psr4[$prefix][] = $paths;
        }
    }

    public function register($prepend = false)
    {
        spl_autoload_register([$this, 'loadClass'], true, $prepend);
    }

    public function loadClass($class)
    {
        $file = $this->findFile($class);
        if ($file) {
            require_once $file;
            return true;
        }
        return false;
    }

    protected function findFile($class)
    {
        if (0 === strpos($class, '\\')) {
            $class = substr($class, 1);
        }

        foreach ($this->psr4 as $prefix => $paths) {
            if (strpos($class, $prefix) === 0) {
                $relativeClass = substr($class, strlen($prefix));
                $file = str_replace('\\', DIRECTORY_SEPARATOR, $relativeClass) . '.php';
                
                foreach ($paths as $path) {
                    $filePath = $path . $file;
                    if (file_exists($filePath)) {
                        return $filePath;
                    }
                }
            }
        }

        return null;
    }
}
PHP;
    
    file_put_contents($projectRoot . '/vendor/composer/ClassLoader.php', $classLoaderContent);
}

// Escreve os arquivos
file_put_contents($autoloadFile, $content);
file_put_contents($classMapFile, $classMapContent);
file_put_contents($filesFile, $filesContent);
file_put_contents($mainAutoloadFile, $mainContent);

// Gera o arquivo principal de autoload
$mainAutoloadPhp = $projectRoot . '/vendor/autoload.php';
$mainAutoloadContent = <<<'PHP'
<?php

// Autoload simples gerado por generate-autoload.php
// Use este arquivo normalmente: require_once 'vendor/autoload.php';

// Define o diretório raiz do projeto
define('PROJECT_ROOT', __DIR__ . '/..');

// Registra autoload manualmente se o real não existir
function autoloadPsr4($class)
{
    $psr4 = [
        'App\\' => 'app/',
        'App\\Model\\' => 'app/Model/',
        'App\\Controller\\' => 'app/Controller/',
        'App\\View\\' => 'app/View/',
        'Core\\' => 'Core/',
    ];

    $prefix = strtok($class, '\\');
    $prefix .= '\\';
    
    if (isset($psr4[$prefix])) {
        $relativeClass = substr($class, strlen($prefix));
        $file = PROJECT_ROOT . '/' . $psr4[$prefix] . str_replace('\\', '/', $relativeClass) . '.php';
        
        if (file_exists($file)) {
            require_once $file;
            return true;
        }
    }
    
    return false;
}

spl_autoload_register('autoloadPsr4');

// Carrega arquivos de configuração
$configFiles = [
    'Config/db/conexao.php',
    'Core/autenticacao.php',
];

foreach ($configFiles as $file) {
    $filePath = PROJECT_ROOT . '/' . $file;
    if (file_exists($filePath)) {
        require_once $filePath;
    }
}
PHP;

file_put_contents($mainAutoloadPhp, $mainAutoloadContent);

// Output
echo "✅ Autoload gerado com sucesso!\n\n";
echo "Arquivos criados:\n";
echo "  ✓ vendor/autoload.php\n";
echo "  ✓ vendor/composer/autoload_psr4.php\n";
echo "  ✓ vendor/composer/autoload_files.php\n";
echo "  ✓ vendor/composer/autoload_classmap.php\n";
echo "  ✓ vendor/composer/autoload_real.php\n";
echo "  ✓ vendor/composer/ClassLoader.php\n\n";
echo "Agora você pode usar:\n";
echo "  require_once 'vendor/autoload.php';\n";
echo "  use App\\Model\\Usuario;\n\n";
echo "✨ Sistema pronto para usar!\n";
