<?php

namespace App\Models;

class Curso
{
    public static function listar(): array
    {
        return [
            [
                'id' => 1,
                'nome' => 'Técnico em Informática',
                'descricao_curta' => 'Desenvolva sistemas, redes e suporte com foco no mercado digital.',
                'descricao_completa' => 'Curso com foco em desenvolvimento de softwares, infraestrutura de redes, suporte técnico e segurança digital. Ideal para quem quer atuar em empresas de tecnologia, startups ou áreas de TI de grandes organizações.',
                'duracao' => '2 anos',
                'modalidade' => 'Presencial',
                'unidades' => ['Centro', 'Unidade Sul'],
                'grade_resumida' => ['Programação', 'Redes de Computadores', 'Banco de Dados', 'Suporte Técnico'],
                'disciplinas' => ['Lógica de Programação', 'Sistemas Operacionais', 'Redes', 'Banco de Dados', 'Segurança da Informação'],
                'beneficios' => ['Laboratórios de ponta', 'Aulas práticas', 'Mentoria profissional', 'Apoio à colocação'],
                'area' => 'Tecnologia',
                'mercado_trabalho' => 'O mercado busca profissionais em suporte técnico, desenvolvimento web, infraestrutura de redes e consultoria de TI.',
                'certificacao' => 'Certificado Técnico reconhecido pelo MEC',
                'carga_horaria' => '1200h',
                'requisitos' => ['Ensino Médio completo', 'Conhecimentos básicos de informática'],
                'turno' => 'Manhã/Tarde',
                'status' => 'Inscrições abertas',
                'diferenciais' => ['Projeto final de desenvolvimento de software', 'Preparação para certificações de TI', 'Parcerias com empresas locais'],
                'oportunidades' => ['Técnico de Suporte', 'Analista de Redes', 'Desenvolvedor Júnior'],
                'faixa_salarial' => 'R$ 2.200 - R$ 4.500',
                'popularidade' => 95,
                'novo' => false,
                'inscricoes_abertas' => true,
                'recomendado' => true,
                'destaque' => true,
                'popular' => true,
            ],
            [
                'id' => 2,
                'nome' => 'Desenvolvimento de Sistemas',
                'descricao_curta' => 'Projete aplicações web, mobile e APIs com práticas modernas.',
                'descricao_completa' => 'Formação técnica em desenvolvimento de sistemas com foco em programação orientada a objetos, interfaces de usuário, bancos de dados e integração de APIs. Perfeito para quem quer criar soluções digitais completas.',
                'duracao' => '2 anos',
                'modalidade' => 'Híbrido',
                'unidades' => ['Centro'],
                'grade_resumida' => ['Linguagens de Programação', 'Banco de Dados', 'Desenvolvimento Web', 'Metodologias Ágeis'],
                'disciplinas' => ['Programação Web', 'Java', 'PHP', 'JavaScript', 'UX/UI'],
                'beneficios' => ['Aulas remotas e presenciais', 'Projetos em equipe', 'Ferramentas de desenvolvimento modernas'],
                'area' => 'Tecnologia',
                'mercado_trabalho' => 'Alta demanda por desenvolvedores front-end, back-end, mobile e analistas de sistemas.',
                'certificacao' => 'Certificação Técnica de Programação',
                'carga_horaria' => '1200h',
                'requisitos' => ['Ensino Médio completo', 'Interesse por lógica e desenvolvimento'],
                'turno' => 'Tarde',
                'status' => 'Inscrições abertas',
                'diferenciais' => ['Metodologias ágeis', 'Hackathons internos', 'Portfolio profissional'],
                'oportunidades' => ['Desenvolvedor Web', 'Analista de Sistemas', 'Engenheiro de Software Júnior'],
                'faixa_salarial' => 'R$ 2.500 - R$ 5.800',
                'popularidade' => 90,
                'novo' => false,
                'inscricoes_abertas' => true,
                'recomendado' => true,
                'destaque' => true,
                'popular' => true,
            ],
            [
                'id' => 3,
                'nome' => 'Administração',
                'descricao_curta' => 'Forme-se em gestão empresarial, finanças e liderança.',
                'descricao_completa' => 'Curso técnico em administração com foco em gestão de negócios, finanças, marketing e planejamento estratégico. Ideal para quem busca atuar em empresas de todos os portes.',
                'duracao' => '2 anos',
                'modalidade' => 'Presencial',
                'unidades' => ['Centro', 'Unidade Norte'],
                'grade_resumida' => ['Finanças', 'Marketing', 'RH', 'Planejamento Estratégico'],
                'disciplinas' => ['Gestão Financeira', 'Logística', 'Marketing Digital', 'Empreendedorismo'],
                'beneficios' => ['Simuladores empresariais', 'Networking com empresas', 'Estágio orientado'],
                'area' => 'Gestão',
                'mercado_trabalho' => 'Formação voltada para cargos administrativos, analistas financeiros, assistentes de RH e consultoria em negócios.',
                'certificacao' => 'Certificado Técnico em Administração',
                'carga_horaria' => '1000h',
                'requisitos' => ['Ensino Médio completo'],
                'turno' => 'Manhã',
                'status' => 'Em breve',
                'diferenciais' => ['Estágio supervisionado', 'Workshops de liderança', 'Mentoria de carreira'],
                'oportunidades' => ['Auxiliar Administrativo', 'Analista de Marketing', 'Assistente Financeiro'],
                'faixa_salarial' => 'R$ 1.800 - R$ 4.000',
                'popularidade' => 72,
                'novo' => false,
                'inscricoes_abertas' => false,
                'recomendado' => false,
                'destaque' => false,
                'popular' => true,
            ],
            [
                'id' => 4,
                'nome' => 'Recursos Humanos',
                'descricao_curta' => 'Aprenda a gerir pessoas, recrutamento e clima organizacional.',
                'descricao_completa' => 'Curso técnico para quem deseja trabalhar com seleção, desenvolvimento de pessoas, legislação trabalhista e cultura organizacional. Ideal para equipes de RH, consultorias e startups.',
                'duracao' => '18 meses',
                'modalidade' => 'Híbrido',
                'unidades' => ['Unidade Sul'],
                'grade_resumida' => ['Recrutamento', 'Treinamento', 'Legislação Trabalhista', 'Clima Organizacional'],
                'disciplinas' => ['Gestão de Pessoas', 'Psicologia Organizacional', 'Administração de Pessoal', 'Comunicação'],
                'beneficios' => ['Aulas flexíveis', 'Case studies', 'Atendimento individualizado'],
                'area' => 'Gestão',
                'mercado_trabalho' => 'Demanda por analistas de RH, recrutadores e especialistas em desenvolvimento humano permanece alta.',
                'certificacao' => 'Certificado Técnico em RH',
                'carga_horaria' => '900h',
                'requisitos' => ['Ensino Médio completo'],
                'turno' => 'Noite',
                'status' => 'Inscrições abertas',
                'diferenciais' => ['Parcerias com empresas', 'Simulações de entrevista', 'Portfólio de competências'],
                'oportunidades' => ['Analista de RH', 'Recrutador', 'Coordenador de Treinamento'],
                'faixa_salarial' => 'R$ 2.000 - R$ 4.200',
                'popularidade' => 85,
                'novo' => false,
                'inscricoes_abertas' => true,
                'recomendado' => true,
                'destaque' => false,
                'popular' => true,
            ],
            [
                'id' => 5,
                'nome' => 'Enfermagem',
                'descricao_curta' => 'Formação técnica para atendimento clínico e cuidado de pacientes.',
                'descricao_completa' => 'Curso técnico em enfermagem com práticas em atendimento hospitalar, primeiros socorros, administração de medicamentos e humanização do cuidado. Perfeito para quem busca carreira estável na área da saúde.',
                'duracao' => '2 anos',
                'modalidade' => 'Presencial',
                'unidades' => ['Unidade Norte'],
                'grade_resumida' => ['Anatomia', 'Procedimentos Clínicos', 'Enfermagem Hospitalar', 'Segurança do Paciente'],
                'disciplinas' => ['Anatomia e Fisiologia', 'Técnicas de Enfermagem', 'Biossegurança', 'Ética Profissional'],
                'beneficios' => ['Estágio em hospitais', 'Simulação clínica realista', 'Apoio na transição para o mercado'],
                'area' => 'Saúde',
                'mercado_trabalho' => 'Fortes oportunidades em hospitais, clínicas, unidades básicas de saúde e atendimento domiciliar.',
                'certificacao' => 'Certificado Técnico em Enfermagem',
                'carga_horaria' => '1400h',
                'requisitos' => ['Ensino Médio completo', 'Interesse pela área da saúde'],
                'turno' => 'Integral',
                'status' => 'Inscrições abertas',
                'diferenciais' => ['Aulas práticas em laboratórios', 'Apoio emergencial', 'Rede de contatos hospitalares'],
                'oportunidades' => ['Técnico em Enfermagem', 'Assistente de Saúde', 'Cuidador Clínico'],
                'faixa_salarial' => 'R$ 2.900 - R$ 5.200',
                'popularidade' => 88,
                'novo' => true,
                'inscricoes_abertas' => true,
                'recomendado' => true,
                'destaque' => true,
                'popular' => true,
            ],
            [
                'id' => 6,
                'nome' => 'Saúde Bucal',
                'descricao_curta' => 'Qualifique-se em apoio odontológico e biossegurança.',
                'descricao_completa' => 'Curso técnico de saúde bucal com foco em prevenção, atendimento odontológico assistido e cuidados de biossegurança. Ideal para clínicas, laboratórios e unidades de saúde.',
                'duracao' => '1 ano',
                'modalidade' => 'Presencial',
                'unidades' => ['Centro'],
                'grade_resumida' => ['Atendimento Odontológico', 'Biossegurança', 'Radiologia Odontológica'],
                'disciplinas' => ['Higiene Oral', 'Instrumentação Odontológica', 'Anatomia Dental', 'Ética e Humanização'],
                'beneficios' => ['Laboratório de simulação', 'Parcerias com clínicas', 'Aulas práticas intensivas'],
                'area' => 'Saúde',
                'mercado_trabalho' => 'Perfil procurado em clínicas odontológicas, unidades de saúde e consultórios particulares.',
                'certificacao' => 'Certificado Técnico em Saúde Bucal',
                'carga_horaria' => '800h',
                'requisitos' => ['Ensino Médio completo'],
                'turno' => 'Integral',
                'status' => 'Em breve',
                'diferenciais' => ['Prática em laboratório', 'Apoio para carteira de trabalho', 'Orientação de carreira'],
                'oportunidades' => ['Auxiliar em Saúde Bucal', 'Atendente de Clínica Odontológica'],
                'faixa_salarial' => 'R$ 1.900 - R$ 3.600',
                'popularidade' => 66,
                'novo' => false,
                'inscricoes_abertas' => false,
                'recomendado' => false,
                'destaque' => false,
                'popular' => false,
            ],
            [
                'id' => 7,
                'nome' => 'Eletrotécnica',
                'descricao_curta' => 'Especialize-se em instalações elétricas e automação industrial.',
                'descricao_completa' => 'Formação técnica em eletrotécnica com destaque para instalações elétricas, manutenção industrial e automação. Indicada para atuação em indústrias, empresas de energia e construção civil.',
                'duracao' => '2 anos',
                'modalidade' => 'Presencial',
                'unidades' => ['Unidade Sul', 'Centro'],
                'grade_resumida' => ['Circuitos Elétricos', 'Instalações', 'Automação', 'Segurança'],
                'disciplinas' => ['Eletricidade Básica', 'Instalações Prediais', 'Máquinas Elétricas', 'Automação Industrial'],
                'beneficios' => ['Aulas em laboratório de elétrica', 'Projetos reais', 'Rede de contatos do setor'],
                'area' => 'Industrial',
                'mercado_trabalho' => 'Procura por técnicos em energia, manutenção elétrica e projetos de automação continua forte.',
                'certificacao' => 'Certificado Técnico em Eletrotécnica',
                'carga_horaria' => '1200h',
                'requisitos' => ['Ensino Médio completo', 'Interesse por eletricidade'],
                'turno' => 'Noite',
                'status' => 'Inscrições abertas',
                'diferenciais' => ['Aulas práticas de campo', 'Projetos de automação', 'Parcerias industriais'],
                'oportunidades' => ['Técnico em Eletrotécnica', 'Instalador', 'Manutenção Industrial'],
                'faixa_salarial' => 'R$ 2.500 - R$ 5.000',
                'popularidade' => 82,
                'novo' => false,
                'inscricoes_abertas' => true,
                'recomendado' => true,
                'destaque' => false,
                'popular' => true,
            ],
            [
                'id' => 8,
                'nome' => 'Mecânica',
                'descricao_curta' => 'Aprimore conhecimentos em manutenção e tecnologia industrial.',
                'descricao_completa' => 'Curso técnico em mecânica com ênfase em manutenção de máquinas, processos industriais e leitura técnica de projetos. Ideal para quem busca trabalhar em indústria, manutenção predial e serviços especializados.',
                'duracao' => '2 anos',
                'modalidade' => 'Presencial',
                'unidades' => ['Unidade Norte'],
                'grade_resumida' => ['Desenho Técnico', 'Mecânica Geral', 'Processos de Fabricação'],
                'disciplinas' => ['Mecânica de máquinas', 'Metrologia', 'Usinagem', 'Instalação e manutenção'],
                'beneficios' => ['Oficina equipada', 'Aulas com foco prático', 'Projetos cooperativos'],
                'area' => 'Industrial',
                'mercado_trabalho' => 'Vagas em manutenção industrial, usinagem, mecânica automotiva e processos de produção.',
                'certificacao' => 'Certificado Técnico em Mecânica',
                'carga_horaria' => '1200h',
                'requisitos' => ['Ensino Médio completo'],
                'turno' => 'Noite',
                'status' => 'Inscrições abertas',
                'diferenciais' => ['Oficina prática completa', 'Projetos em equipe', 'Componente de empreendedorismo'],
                'oportunidades' => ['Técnico em Mecânica', 'Operador de Usinagem', 'Supervisor de Manutenção'],
                'faixa_salarial' => 'R$ 2.300 - R$ 4.700',
                'popularidade' => 78,
                'novo' => false,
                'inscricoes_abertas' => true,
                'recomendado' => false,
                'destaque' => false,
                'popular' => true,
            ],
            [
                'id' => 9,
                'nome' => 'Marketing Digital',
                'descricao_curta' => 'Domine campanhas, redes sociais e análise de resultados.',
                'descricao_completa' => 'Formação técnica em marketing digital, estratégias de redes sociais, criação de campanhas e análise de dados. Ideal para profissionais que desejam trabalhar com comunicação e vendas online.',
                'duracao' => '18 meses',
                'modalidade' => 'Híbrido',
                'unidades' => ['Centro'],
                'grade_resumida' => ['Marketing Digital', 'Comunicação', 'Análise de Dados', 'SEO e SEM'],
                'disciplinas' => ['Marketing de Conteúdo', 'Analytics', 'Publicidade Online', 'Social Media'],
                'beneficios' => ['Laboratório de mídias sociais', 'Projetos reais', 'Conexão com empresas'],
                'area' => 'Gestão',
                'mercado_trabalho' => 'Alta demanda em agências, negócios digitais, e-commerce e setores de vendas.',
                'certificacao' => 'Certificado Técnico em Marketing Digital',
                'carga_horaria' => '900h',
                'requisitos' => ['Ensino Médio completo', 'Criatividade e comunicação'],
                'turno' => 'Tarde',
                'status' => 'Novo',
                'diferenciais' => ['Workshop de branding', 'Estratégias de tráfego pago', 'Portfólio de campanhas'],
                'oportunidades' => ['Analista de Marketing', 'Social Media', 'Planejador de Mídia'],
                'faixa_salarial' => 'R$ 2.100 - R$ 4.200',
                'popularidade' => 80,
                'novo' => true,
                'inscricoes_abertas' => false,
                'recomendado' => true,
                'destaque' => true,
                'popular' => true,
            ],
            [
                'id' => 10,
                'nome' => 'Logística',
                'descricao_curta' => 'Gestão da cadeia de suprimentos e operações logísticas.',
                'descricao_completa' => 'Curso técnico em logística voltado para transporte, armazenagem, controle de estoque e processos operacionais. Ótimo para quem busca atuar em centros de distribuição, transporte e comércio.',
                'duracao' => '1 ano',
                'modalidade' => 'EAD',
                'unidades' => ['Unidade Norte'],
                'grade_resumida' => ['Planejamento Logístico', 'Armazenagem', 'Transporte', 'Gestão de Estoques'],
                'disciplinas' => ['Logística de Distribuição', 'Custos Logísticos', 'Sistemas de Informação', 'Segurança Operacional'],
                'beneficios' => ['Flexibilidade EAD', 'Projetos em tempo real', 'Simulações de cadeia de suprimentos'],
                'area' => 'Gestão',
                'mercado_trabalho' => 'Ampla demanda em e-commerce, logística de transportes, armazenagem e centros de distribuição.',
                'certificacao' => 'Certificado Técnico em Logística',
                'carga_horaria' => '700h',
                'requisitos' => ['Ensino Médio completo'],
                'turno' => 'EAD',
                'status' => 'Inscrições abertas',
                'diferenciais' => ['Acesso a plataforma digital', 'Mentoria online', 'Simulações de rotas'],
                'oportunidades' => ['Analista de Logística', 'Supervisor de Estoque', 'Planejador de Transportes'],
                'faixa_salarial' => 'R$ 2.000 - R$ 4.000',
                'popularidade' => 76,
                'novo' => false,
                'inscricoes_abertas' => true,
                'recomendado' => false,
                'destaque' => false,
                'popular' => true,
            ],
        ];
    }
}
